FROM maven:3.8.3-openjdk-17 AS build
RUN mkdir /project
COPY . /project
WORKDIR /project
RUN mvn clean package -DskipTests


FROM eclipse-temurin:17-jre-alpine AS deployable
RUN apk add dumb-init
RUN mkdir /app
RUN addgroup --system javauser && adduser -S -s /bin/false -G javauser javauser
COPY --from=build /project/target/example-vertx-0.0.1-fat.jar /app/example-vertx-0.0.1-fat.jar


WORKDIR /app
RUN chown -R javauser:javauser /app
USER javauser
CMD "dumb-init" "java" "-jar" "example-vertx-0.0.1-fat.jar"

