micronaut:
  application:
    name: example
  security:
    enabled: true
    authentication:
      providers:
        myAuthProvider:
          enabled: true
          class: id.passageidentity.passage4j.example_micronaut.security.TokenAuthenticationProvider
passage:
  app-id: ${PASSAGE_APP_ID}
  api-key: ${PASSAGE_API_KEY}
netty:
  default:
    allocator:
      max-order: 3
